//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jvw.DevToys.SemverCalculator.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Jvw.DevToys.SemverCalculator.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semver Calculator.
        /// </summary>
        public static string AccessibleNameResourceName {
            get {
                return ResourceManager.GetString("AccessibleNameResourceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any version compatible with 1.2 (&gt;=1.2.0-0 &lt;2.0.0-0).
        /// </summary>
        public static string CheatSheetAnyCompatibleWithDescription {
            get {
                return ResourceManager.GetString("CheatSheetAnyCompatibleWithDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any version.
        /// </summary>
        public static string CheatSheetAnyDescription {
            get {
                return ResourceManager.GetString("CheatSheetAnyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any version starting with 1.2 (&gt;=1.2.0-0 &lt;1.3.0-0).
        /// </summary>
        public static string CheatSheetAnyStartingWithDescription {
            get {
                return ResourceManager.GetString("CheatSheetAnyStartingWithDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Between 1.2.3 and 2.3.4 (&gt;=1.2.3 &lt;=2.3.4).
        /// </summary>
        public static string CheatSheetBetweenDescription {
            get {
                return ResourceManager.GetString("CheatSheetBetweenDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string CheatSheetColumnDescriptionTitle {
            get {
                return ResourceManager.GetString("CheatSheetColumnDescriptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example.
        /// </summary>
        public static string CheatSheetColumnExampleTitle {
            get {
                return ResourceManager.GetString("CheatSheetColumnExampleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syntax.
        /// </summary>
        public static string CheatSheetColumnSyntaxTitle {
            get {
                return ResourceManager.GetString("CheatSheetColumnSyntaxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compatible with 1.2.3 (&gt;=1.2.3 &lt;2.0.0).
        /// </summary>
        public static string CheatSheetCompatibleWithDescription {
            get {
                return ResourceManager.GetString("CheatSheetCompatibleWithDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explanation.
        /// </summary>
        public static string CheatSheetExplanationTitle {
            get {
                return ResourceManager.GetString("CheatSheetExplanationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stable for first public release.
        /// </summary>
        public static string CheatSheetFirstPublicDescription {
            get {
                return ResourceManager.GetString("CheatSheetFirstPublicDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greater than 1.2.3.
        /// </summary>
        public static string CheatSheetGreaterThanDescription {
            get {
                return ResourceManager.GetString("CheatSheetGreaterThanDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greater than or equal to 1.2.3.
        /// </summary>
        public static string CheatSheetGreaterThanOrEqualDescription {
            get {
                return ResourceManager.GetString("CheatSheetGreaterThanOrEqualDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used for initial development.
        /// </summary>
        public static string CheatSheetInitialDevelopmentDescription {
            get {
                return ResourceManager.GetString("CheatSheetInitialDevelopmentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Less than 1.2.3.
        /// </summary>
        public static string CheatSheetLessThanDescription {
            get {
                return ResourceManager.GetString("CheatSheetLessThanDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Less than or equal to 1.2.3.
        /// </summary>
        public static string CheatSheetLessThanOrEqualDescription {
            get {
                return ResourceManager.GetString("CheatSheetLessThanOrEqualDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incompatible API changes.
        /// </summary>
        public static string CheatSheetMajorDescription {
            get {
                return ResourceManager.GetString("CheatSheetMajorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAJOR.MINOR.PATCH.
        /// </summary>
        public static string CheatSheetMajorMinorPatchTitle {
            get {
                return ResourceManager.GetString("CheatSheetMajorMinorPatchTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Improved functionality or new features (backwards-compatible).
        /// </summary>
        public static string CheatSheetMinorDescription {
            get {
                return ResourceManager.GetString("CheatSheetMinorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bug fixes (backwards-compatible).
        /// </summary>
        public static string CheatSheetPatchDescription {
            get {
                return ResourceManager.GetString("CheatSheetPatchDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reasonably close to 1.2.3 (&gt;=1.2.3 &lt;1.3.0).
        /// </summary>
        public static string CheatSheetReasonablyCloseDescription {
            get {
                return ResourceManager.GetString("CheatSheetReasonablyCloseDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syntax.
        /// </summary>
        public static string CheatSheetSyntaxTitle {
            get {
                return ResourceManager.GetString("CheatSheetSyntaxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cheat sheet.
        /// </summary>
        public static string CheatSheetTitle {
            get {
                return ResourceManager.GetString("CheatSheetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A calculator for semver..
        /// </summary>
        public static string DescriptionResourceName {
            get {
                return ResourceManager.GetString("DescriptionResourceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclude pre-releases.
        /// </summary>
        public static string ExcludePreReleaseTitle {
            get {
                return ResourceManager.GetString("ExcludePreReleaseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By using this extension you agree that this extension is making HTTP calls to registry.npmjs.org..
        /// </summary>
        public static string HttpAgreementInfoBarDescription {
            get {
                return ResourceManager.GetString("HttpAgreementInfoBarDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include pre-releases.
        /// </summary>
        public static string IncludePreReleaseTitle {
            get {
                return ResourceManager.GetString("IncludePreReleaseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semver Calculator.
        /// </summary>
        public static string LongDisplayTitleResourceName {
            get {
                return ResourceManager.GetString("LongDisplayTitleResourceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semver Calculator DEBUG.
        /// </summary>
        public static string LongDisplayTitleResourceNameDebug {
            get {
                return ResourceManager.GetString("LongDisplayTitleResourceNameDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to fetch package..
        /// </summary>
        public static string PackageFetchFailureError {
            get {
                return ResourceManager.GetString("PackageFetchFailureError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load package versions.
        /// </summary>
        public static string PackageLoadButtonText {
            get {
                return ResourceManager.GetString("PackageLoadButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NPM package name.
        /// </summary>
        public static string PackageNameInputTitle {
            get {
                return ResourceManager.GetString("PackageNameInputTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package name is required..
        /// </summary>
        public static string PackageNameRequiredError {
            get {
                return ResourceManager.GetString("PackageNameRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semver Calculator.
        /// </summary>
        public static string ShortDisplayTitleResourceName {
            get {
                return ResourceManager.GetString("ShortDisplayTitleResourceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semver Calculator DEBUG.
        /// </summary>
        public static string ShortDisplayTitleResourceNameDebug {
            get {
                return ResourceManager.GetString("ShortDisplayTitleResourceNameDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version range.
        /// </summary>
        public static string VersionRangeInputTitle {
            get {
                return ResourceManager.GetString("VersionRangeInputTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version range appears to be not valid..
        /// </summary>
        public static string VersionRangeInvalidError {
            get {
                return ResourceManager.GetString("VersionRangeInvalidError", resourceCulture);
            }
        }
    }
}
