//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jvw.DevToys.SemverCalculator.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Jvw.DevToys.SemverCalculator.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semver Calculator.
        /// </summary>
        public static string AccessibleNameResourceName {
            get {
                return ResourceManager.GetString("AccessibleNameResourceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A calculator for semver..
        /// </summary>
        public static string DescriptionResourceName {
            get {
                return ResourceManager.GetString("DescriptionResourceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclude pre-releases.
        /// </summary>
        public static string ExcludePreReleaseTitle {
            get {
                return ResourceManager.GetString("ExcludePreReleaseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include pre-releases.
        /// </summary>
        public static string IncludePreReleaseTitle {
            get {
                return ResourceManager.GetString("IncludePreReleaseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semver Calculator.
        /// </summary>
        public static string LongDisplayTitleResourceName {
            get {
                return ResourceManager.GetString("LongDisplayTitleResourceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semver Calculator DEBUG.
        /// </summary>
        public static string LongDisplayTitleResourceNameDebug {
            get {
                return ResourceManager.GetString("LongDisplayTitleResourceNameDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to fetch package..
        /// </summary>
        public static string PackageFetchFailureError {
            get {
                return ResourceManager.GetString("PackageFetchFailureError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load package versions.
        /// </summary>
        public static string PackageLoadButtonText {
            get {
                return ResourceManager.GetString("PackageLoadButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NPM package name.
        /// </summary>
        public static string PackageNameInputTitle {
            get {
                return ResourceManager.GetString("PackageNameInputTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package name is required..
        /// </summary>
        public static string PackageNameRequiredError {
            get {
                return ResourceManager.GetString("PackageNameRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semver Calculator.
        /// </summary>
        public static string ShortDisplayTitleResourceName {
            get {
                return ResourceManager.GetString("ShortDisplayTitleResourceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semver Calculator DEBUG.
        /// </summary>
        public static string ShortDisplayTitleResourceNameDebug {
            get {
                return ResourceManager.GetString("ShortDisplayTitleResourceNameDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version range.
        /// </summary>
        public static string VersionRangeInputTitle {
            get {
                return ResourceManager.GetString("VersionRangeInputTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version range appears to be not valid..
        /// </summary>
        public static string VersionRangeInvalidError {
            get {
                return ResourceManager.GetString("VersionRangeInvalidError", resourceCulture);
            }
        }
    }
}
