name: .NET Build, Test, and Publish Nuget Package

on:
  push:
    branches:
      - "**"
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
  pull_request:
    branches:
      - "**"
env:
  VERSION: 0.0.0

defaults:
  run:
    working-directory: "Jvw.DevToys.SemverCalculator"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set version variable
        if: ${{ github.ref_type == 'tag' }}
        env:
          TAG: ${{ github.ref_name }}
        run: echo "VERSION=${TAG#v}" >> $GITHUB_ENV

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8"

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore /p:Version=$VERSION

      - name: Test
        run: dotnet test --no-build --verbosity normal

      - name: Pack NuGet package
        run: dotnet pack --output nupkgs /p:PackageVersion=$VERSION

      - name: Upload NuGet package
        uses: actions/upload-artifact@v4
        with:
          name: nupkgs
          path: "**/nupkgs/**"

      - name: Publish NuGet package
        if: github.ref_type == 'tag' && startsWith(github.ref, 'refs/tags/v')
        run: dotnet nuget push nupkgs/*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json
